from .code_duplication import detect_code_duplication
from .collaboration_efficiency import analyze_collaboration
from .complexity import analyze_complexity
from .dependency_change import detect_dependency_changes
from .embedding import embed_text
from .risk import compute_risk
from .security_scan import scan_security_vulnerabilities
from .summary import generate_basic_summary
from .test_coverage import analyze_test_coverage